#!/usr/bin/env bash
set -euo pipefail

readonly baseline='f571ac5243518387c5b1a81c818dd8ffdd8db2de'
readonly prohibited='codex|generated by([^[:alnum:]_]|$)|ai-generated|vibe coded|vibe coding|internal prompt|git directive|chatgpt|claude|gemini|gpt[- ]?[0-9]|llama|mistral|copilot'
readonly prohibited_branch='(^|/)(codex|agent|ai)(/|$)'

failures=0

reject_text() {
  local label="$1"
  local value="$2"
  if printf '%s\n' "$value" | grep --extended-regexp --ignore-case --quiet "$prohibited"; then
    printf 'Prohibited public text in %s.\n' "$label" >&2
    failures=$((failures + 1))
  fi
}

branch="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME:-$(git branch --show-current)}}"
reject_text 'branch name' "$branch"
if printf '%s\n' "$branch" | grep --extended-regexp --ignore-case --quiet "$prohibited_branch"; then
  printf 'Prohibited branch category: %s\n' "$branch" >&2
  failures=$((failures + 1))
fi

if [[ "${GITHUB_EVENT_NAME:-}" == 'pull_request' ]]; then
  if [[ -z "${GITHUB_EVENT_PATH:-}" || ! -f "$GITHUB_EVENT_PATH" ]]; then
    printf 'Pull request event payload is unavailable.\n' >&2
    failures=$((failures + 1))
  else
    reject_text 'pull request title' "$(jq --raw-output '.pull_request.title // ""' "$GITHUB_EVENT_PATH")"
    reject_text 'pull request body' "$(jq --raw-output '.pull_request.body // ""' "$GITHUB_EVENT_PATH")"
    reject_text 'pull request head ref' "$(jq --raw-output '.pull_request.head.ref // ""' "$GITHUB_EVENT_PATH")"
  fi
fi

if ! git cat-file -e "${baseline}^{commit}"; then
  printf 'Independent-repository baseline commit is missing.\n' >&2
  exit 1
fi
if ! git merge-base --is-ancestor "$baseline" HEAD; then
  printf 'Current history does not descend from the independent-repository baseline.\n' >&2
  exit 1
fi

new_messages="$(git log --format='%B' "${baseline}..HEAD")"
reject_text 'new commit messages' "$new_messages"
if printf '%s\n' "$new_messages" | grep --extended-regexp --ignore-case --quiet '^co-authored-by:'; then
  printf 'New commit messages contain a co-author trailer.\n' >&2
  failures=$((failures + 1))
fi

mapfile -d '' public_files < <(
  git ls-files -z -- '*.md' '.github/ISSUE_TEMPLATE/*' '.github/pull_request_template.md'
)
for file in "${public_files[@]}"; do
  reject_text "$file" "$(<"$file")"
done

if (( failures > 0 )); then
  printf 'Public-surface policy failed with %d finding(s).\n' "$failures" >&2
  exit 1
fi

printf 'Public-surface policy passed for %d files and branch %s.\n' "${#public_files[@]}" "$branch"
